### ISSUE TITLE
Ninja builds fail

### ISSUE THREAD

**Issue by GBuella** [pmem/pmemfile#144]
The way gtest is added in tests/posix/CMakeLists.txt works well with makefiles, but apparently  something is missing for ninja to understand the dependencies.

```
~/code/pmemfile$ mkdir nbuild && cd nbuild
~/code/pmemfile/nbuild$ cmake -G Ninja .. > /dev/null
~/code/pmemfile/nbuild$ ninja
ninja: error: 'tests/posix/gtest/src/gtest-build/googlemock/gtest/libgtest.a', needed by 'tests/posix/file_crash', missing and no known rule to make it
```

**Comment by marcinslusarz** [comment]
Already fixed.

**Comment by GBuella** [comment]
Oh, I'm also planning to add a travis configuration that uses builds with ninja.
