### ISSUE TITLE
preload: incomplete environment setup

### ISSUE THREAD

**Issue by mslusarz** [pmem/pmemfile#207]
libpmemfile does not:
- notify libpmemfile-posix about current user credentials (ruid, rgid, fsuid, fsgid, euid, egid, groups, capabilites) and its changes
- notify libpmemfile-posix about umask and its changes

It affects a lot of tests in pjdfstest.

**Comment by marcinslusarz** [comment]
ruid, rgid, fsuid, fsgid, euid, egid, groups and umask are already handled. Only capabilities left.
