### ISSUE TITLE
Cached pointers in pmemfile struct's can be invalidated by other file operations.

### ISSUE THREAD

**Issue by GBuella** [pmem/pmemfile#79]
Certain file operations can remove blocks from a file on media, which can result in some pmemfile structs referring to blocks to be invalidated. Currently there is no trivial way to fix it.

**Comment by marcinslusarz** [comment]
We can store generation id in pmemfile_file and pmemfile_vinode, bump the one in pmemfile_vinode every time cached information in pmemfile_file is invalidated and check they are the same on access to pmemfile_file.
