### ISSUE TITLE
It's not possible to rm -r directory with files (fcntl)

### ISSUE THREAD

**Issue by mramotowski** [pmem/pmemfile#88]
> LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libpmemfile.so PMEMFILE_POOLS=/tmp/mountpoint:/mnt/pmem/pmemfile_pool ls testdir
> no-such-file  test2.db  test3.db  test.db
> 
> export INTERCEPT_LOG=intercept.log
> export PMEMFILE_PRELOAD_LOG=pmemfile_preload.log
> export PMEMFILECORE_LOG_LEVEL=4
> export PMEMFILECORE_LOG_FILE=pmemfile-core.log
> export PMEM_IS_PMEM_FORCE=1
> LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libpmemfile.so PMEMFILE_POOLS=/tmp/mountpoint:/mnt/pmem/pmemfile_pool rm -r testdir
> 
>  cat intercept.log 
> tempfile=$(mktemp) ; tempfile2=$(mktemp) ; grep "^/" $0 | cut -d " " -f 1,2 | sed "s/^/addr2line -p -f -e /" > $tempfile ; { echo ; . $tempfile ; echo ; } > $tempfile2 ; paste $tempfile2 $0 ; exit 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6f78 -- getcwd("0\x1c", 1024) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6f78 -- getcwd("/tmp/mountpoint", 1024) = 16
> /lib/x86_64-linux-gnu/libc.so.6 0xf6003 -- stat("/tmp/mountpoint", 0x7ffdb7d28b40) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6003 -- stat("/tmp/mountpoint", 0x7ffdb7d28b40) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 00) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 00) = 6
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(6, 0x7ffdb7d268c0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(6, 0x7ffdb7d268c0) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(6) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(6) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 00) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 00) = 6
> /lib/x86_64-linux-gnu/libc.so.6 0xf6bc5 -- flock(6, 6) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6bc5 -- flock(6, 6) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 00) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 00) = 7
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(7, 0x7ffdb7d267e0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(7, 0x7ffdb7d267e0) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(7) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(7) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6003 -- stat("/mnt/pmem/pmemfile_pool", 0x7ffdb7d288d0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6003 -- stat("/mnt/pmem/pmemfile_pool", 0x7ffdb7d288d0) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf667e -- read(6, "", 11) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf667e -- read(6, "PMEMOBJ\0\x03\0\0", 11) = 11
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(6) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(6) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 00) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 00) = 6
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(6, 0x7ffdb7d26890) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(6, 0x7ffdb7d26890) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(6) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(6) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6735 -- access("/mnt/pmem/pmemfile_pool", 0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6735 -- access("/mnt/pmem/pmemfile_pool", 0) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDWR, 040000000) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDWR, 040000000) = 6
> /lib/x86_64-linux-gnu/libc.so.6 0xf6bc5 -- flock(6, 6) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6bc5 -- flock(6, 6) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 040000000) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/mnt/pmem/pmemfile_pool", O_RDONLY, 040000000) = 7
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(7, 0x7ffdb7d267e0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(7, 0x7ffdb7d267e0) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(7) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(7) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6003 -- stat("/mnt/pmem/pmemfile_pool", 0x7ffdb7d288d0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6003 -- stat("/mnt/pmem/pmemfile_pool", 0x7ffdb7d288d0) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x0, 1075838976, 1, 34, -1, 0x0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x0, 1075838976, 1, 34, -1, 0x0) = 139691337277440
> /lib/x86_64-linux-gnu/libc.so.6 0x100b55 -- munmap(0x7f0c6c896000, 1075838976) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x100b55 -- munmap(0x7f0c6c896000, 1075838976) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x7f0c6ca00000, 1073741824, 3, 1, 6, 0x0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x7f0c6ca00000, 1073741824, 3, 1, 6, 0x0) = 139691338760192
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x0, 4096, 3, 1, 6, 0x0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x0, 4096, 3, 1, 6, 0x0) = 139692444446720
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/proc/self/exe", O_RDONLY, 010) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf645e -- open("/proc/self/exe", O_RDONLY, 010) = 7
> /lib/x86_64-linux-gnu/libc.so.6 0xf667e -- read(7, "", 64) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf667e -- read(7, "\x7fELF\x02\x01\x01\0\0\0\0\0\0\0\0\0\x02\0>\0\x01\0\0\0\x90 @\0\0\0\0\0@\0\0\0\0\0\0\00\xe4\0\0\0\0\0\0\0\0\0\0@\08\0\t\0...", 64) = 64
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(7) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(7) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x100b55 -- munmap(0x7f0cae877000, 4096) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x100b55 -- munmap(0x7f0cae877000, 4096) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xfc227 -- brk(14962688) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xfc227 -- brk(14962688) = 14962688
> /lib/x86_64-linux-gnu/libc.so.6 0x104daf -- open("/sys/devices/system/cpu/online", O_RDONLY | O_CLOEXEC, 0200000) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x104daf -- open("/sys/devices/system/cpu/online", O_RDONLY | O_CLOEXEC, 0200000) = 7
> /lib/x86_64-linux-gnu/libc.so.6 0x104bd6 -- read(7, "", 8192) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x104bd6 -- read(7, "0-7\n", 8192) = 4
> /lib/x86_64-linux-gnu/libc.so.6 0x104e65 -- close(7) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x104e65 -- close(7) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xfc227 -- brk(15097856) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xfc227 -- brk(15097856) = 15097856
> /lib/x86_64-linux-gnu/libc.so.6 0xfc227 -- brk(15233024) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xfc227 -- brk(15233024) = 15233024
> /lib/x86_64-linux-gnu/libc.so.6 0xfc227 -- brk(15368192) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xfc227 -- brk(15368192) = 15368192
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(6) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6d0e -- close(6) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x2c7d1 -- open("/usr/lib/locale/locale-archive", O_RDONLY | O_CLOEXEC, 00) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x2c7d1 -- open("/usr/lib/locale/locale-archive", O_RDONLY | O_CLOEXEC, 00) = 6
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(6, 0x7f0cae075980) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(6, 0x7f0cae075980) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x0, 4228736, 1, 2, 6, 0x0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x0, 4228736, 1, 2, 6, 0x0) = 139691334529024
> /lib/x86_64-linux-gnu/libc.so.6 0x2c876 -- close(6) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x2c876 -- close(6) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xfbaa8 -- ioctl(0, 21505, 140727687482960) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xfbaa8 -- ioctl(0, 21505, 140727687482960) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf60a3 -- lstat("/", 0x7ffdb7d28e30) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf60a3 -- lstat("/", 0x7ffdb7d28e30) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf61b8 -- newfstatat(-100, "testdir", 0xe97558, 256) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf61b8 -- newfstatat(-100, "testdir", 0xe97558, 256) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6548 -- openat(-100, "testdir", O_RDONLY | O_DIRECTORY | O_NOCTTY | O_NOFOLLOW | O_NONBLOCK, 00) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6548 -- openat(-100, "testdir", O_RDONLY | O_DIRECTORY | O_NOCTTY | O_NOFOLLOW | O_NONBLOCK, 00) = 133
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(133, 0x7ffdb7d28ce0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(133, 0x7ffdb7d28ce0) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 3 (F_GETFL), 3) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 3 (F_GETFL), 3) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 2 (F_SETFD), 2) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 2 (F_SETFD), 2) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xc7d39 -- getdents(133, 0xe978a0, 32768) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xc7d39 -- getdents(133, 0xe978a0, 32768) = 176
> /lib/x86_64-linux-gnu/libc.so.6 0xc7825 -- close(133) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xc7825 -- close(133) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xcc6a5 -- geteuid() = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xcc6a5 -- geteuid() = 1000
> /lib/x86_64-linux-gnu/libc.so.6 0xf61b8 -- newfstatat(-100, "testdir", 0x7ffdb7d28db0, 256) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf61b8 -- newfstatat(-100, "testdir", 0x7ffdb7d28db0, 256) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf68a8 -- faccessat(-100, "testdir", 02, 2098) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf68a8 -- faccessat(-100, "testdir", 02, 2098) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6548 -- openat(-100, "testdir", O_RDONLY | O_DIRECTORY | O_NOCTTY | O_NOFOLLOW | O_NONBLOCK, 00) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6548 -- openat(-100, "testdir", O_RDONLY | O_DIRECTORY | O_NOCTTY | O_NOFOLLOW | O_NONBLOCK, 00) = 133
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 1 (F_GETFD), 1) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 1 (F_GETFD), 1) = -95
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(133, 0x7ffdb7d28bf0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(133, 0x7ffdb7d28bf0) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 3 (F_GETFL), 3) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 3 (F_GETFL), 3) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 2 (F_SETFD), 2) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 2 (F_SETFD), 2) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 0 (F_DUPFD), 0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6b05 -- fcntl(133, 0 (F_DUPFD), 0) = -95
> /lib/x86_64-linux-gnu/libc.so.6 0xc7825 -- close(133) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xc7825 -- close(133) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf61b8 -- newfstatat(-100, "testdir", 0x7ffdb7d28db0, 256) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf61b8 -- newfstatat(-100, "testdir", 0x7ffdb7d28db0, 256) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf68a8 -- faccessat(-100, "testdir", 02, 256) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf68a8 -- faccessat(-100, "testdir", 02, 256) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf7ed5 -- unlinkat(4294967196, "testdir", 512) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x79a5d -- open("/usr/share/locale/locale.alias", O_RDONLY | O_CLOEXEC, 0666) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x79a5d -- open("/usr/share/locale/locale.alias", O_RDONLY | O_CLOEXEC, 0666) = 134
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(134, 0x7ffdb7d1e550) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(134, 0x7ffdb7d1e550) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x791ac -- read(134, "", 4096) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x791ac -- read(134, "# Locale name alias data base.\n# Copyright (C) 1996-2016 Free Software Foundation, Inc.\n#\n# This program is free softwa...", 4096) = 2995
> /lib/x86_64-linux-gnu/libc.so.6 0x791ac -- read(134, "", 4096) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x791ac -- read(134, "", 4096) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x78349 -- close(134) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x78349 -- close(134) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY, 03760625641423600) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY, 03760625641423600) = -2
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY, 03760625641423600) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY, 03760625641423600) = -2
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale-langpack/en_US/LC_MESSAGES/libc.mo", O_RDONLY, 03760625641423600) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale-langpack/en_US/LC_MESSAGES/libc.mo", O_RDONLY, 03760625641423600) = -2
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale-langpack/en/LC_MESSAGES/libc.mo", O_RDONLY, 03760625641423600) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale-langpack/en/LC_MESSAGES/libc.mo", O_RDONLY, 03760625641423600) = -2
> /lib/x86_64-linux-gnu/libc.so.6 0xf7ed5 -- unlinkat(4294967196, "testdir", 512) = -39
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale/en_US/LC_MESSAGES/coreutils.mo", O_RDONLY, 03760625641423600) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale/en_US/LC_MESSAGES/coreutils.mo", O_RDONLY, 03760625641423600) = -2
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale/en/LC_MESSAGES/coreutils.mo", O_RDONLY, 03760625641423600) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale/en/LC_MESSAGES/coreutils.mo", O_RDONLY, 03760625641423600) = -2
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale-langpack/en_US/LC_MESSAGES/coreutils.mo", O_RDONLY, 03760625641423600) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale-langpack/en_US/LC_MESSAGES/coreutils.mo", O_RDONLY, 03760625641423600) = -2
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale-langpack/en/LC_MESSAGES/coreutils.mo", O_RDONLY, 03760625641423600) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x30a0d -- open("/usr/share/locale-langpack/en/LC_MESSAGES/coreutils.mo", O_RDONLY, 03760625641423600) = 134
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(134, 0x7ffdb7d28b00) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf6052 -- fstat(134, 0x7ffdb7d28b00) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x0, 619, 1, 2, 134, 0x0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x100ac8 -- mmap(0x0, 619, 1, 2, 134, 0x0) = 139692444446720
> /lib/x86_64-linux-gnu/libc.so.6 0x30b0c -- close(134) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x30b0c -- close(134) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xf66de -- write(2, "rm: ", 4) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf66de -- write(2, "rm: ", 4) = 4
> /lib/x86_64-linux-gnu/libc.so.6 0xf66de -- write(2, "cannot remove 'testdir'", 23) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf66de -- write(2, "cannot remove 'testdir'", 23) = 23
> /lib/x86_64-linux-gnu/libc.so.6 0xf66de -- write(2, ": Directory not empty", 21) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf66de -- write(2, ": Directory not empty", 21) = 21
> /lib/x86_64-linux-gnu/libc.so.6 0xf66de -- write(2, "\n", 1) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0xf66de -- write(2, "\n", 1) = 1
> /lib/x86_64-linux-gnu/libc.so.6 0x106855 -- lseek(0, 0, 1) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x106855 -- lseek(0, 0, 1) = -29
> /lib/x86_64-linux-gnu/libc.so.6 0x78349 -- close(0) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x78349 -- close(0) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x78349 -- close(1) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x78349 -- close(1) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0x78349 -- close(2) = ?
> /lib/x86_64-linux-gnu/libc.so.6 0x78349 -- close(2) = 0
> /lib/x86_64-linux-gnu/libc.so.6 0xcbb96 -- exit_group(1)
> 
> cat pmemfile_preload.log 
> hook_openat("/usr/lib/locale/locale-archive")
> hook_openat("testdir")
> pmemfile_openat(0xe03040, 0xffffffffffffffff, "testdir", 0x30100, 0) = 0xe977f0
> pmemfile_fstat(0x7f0cae34a2c0, 0xe977f0, 0x7ffdb7d28ce0) = 0
> pmemfile_fcntl(0x7f0cae34a2c0, 0xe977f0, 0x3, 0x7ffdb7d28ce0) = 0
> pmemfile_fcntl(0x7f0cae34a2c0, 0xe977f0, 0x2, 0x1) = 0
> pmemfile_getdents(0xe03040, 0xe977f0, 0xe978a0, 32768) = 176
> pmemfile_close(0xe03040, 0xe977f0) = 0
> hook_openat("testdir")
> pmemfile_openat(0xe03040, 0xffffffffffffffff, "testdir", 0x30100, 0) = 0xe977f0
> pmemfile_fcntl(0x7f0cae34a2c0, 0xe977f0, 0x1, 0x0) = -95
> pmemfile_fstat(0x7f0cae34a2c0, 0xe977f0, 0x7ffdb7d28bf0) = 0
> pmemfile_fcntl(0x7f0cae34a2c0, 0xe977f0, 0x3, 0x7ffdb7d28bf0) = 0
> pmemfile_fcntl(0x7f0cae34a2c0, 0xe977f0, 0x2, 0x1) = 0
> pmemfile_fcntl(0x7f0cae34a2c0, 0xe977f0, 0x0, 0x3) = -95
> pmemfile_close(0xe03040, 0xe977f0) = 0
> pmemfile_unlink(0xe03040, "testdir") = -39
> hook_openat("/usr/share/locale/en_US/LC_MESSAGES/coreutils.mo")
> hook_openat("/usr/share/locale/en/LC_MESSAGES/coreutils.mo")
> hook_openat("/usr/share/locale-langpack/en_US/LC_MESSAGES/coreutils.mo")
> hook_openat("/usr/share/locale-langpack/en/LC_MESSAGES/coreutils.mo")
>

**Comment by marcinslusarz** [comment]
"fcntl(133, 1 (F_GETFD), 1) = -95" seems to be the culprit

**Comment by marcinslusarz** [comment]
Blocked on #177

**Comment by marcinslusarz** [comment]
It should be resolved now. Please verify.
